---
- name: add docker apt signing key
  shell: |
    mkdir -p /etc/apt/keyrings
    curl -fsSL {{ docker_key }} | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

- name: add docker repositories
  apt_repository:
    repo: "{{ docker_repo }}"
    filename: docker
    state: present
    update_cache: no

- name: Installing docker packages
  apt:
    name: "{{ docker_packages }}"
    state: present
    update-cache: true
