---
- name: Add Docker user
  become: true
  ansible.builtin.user:
    name: "{{ docker_user }}"
    state: present
    shell: /bin/bash
  register: docker_user_info

- name: Adding Docker user to systemd-journal group
  become: true
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: systemd-journal
    append: true

- name: Ensure Docker user is lingering
  ansible.builtin.stat:
    path: "/var/lib/systemd/linger/{{ docker_user }}"
  register: docker_user_lingering

- name: Enable lingering for the Docker user
  become: true
  ansible.builtin.command: "loginctl enable-linger {{ docker_user }}"
  when: not docker_user_lingering.stat.exists

- name: Create Docker user Ansible tmp dir
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.file:
    path: "{{ docker_user_info.home }}/.ansible/tmp"
    state: directory
    mode: 0700

- name: Create sshd directory for docker
  file:
    path: "{{ docker_user_info.home }}/.ssh"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: 0700

- name: Copy ssh public key for docker
  copy:
    remote_src: yes
    src: /home/vagrant/.ssh/authorized_keys
    dest: "{{ docker_user_info.home }}/.ssh/authorized_keys"
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: 0600
