# read nodes
- hosts: local
  become: true
  become_user: "{{ act_as }}"

  vars:
    node_group: "consul"
    node_read_only: true

  vars_files:
    - vars/variables.prod.yml

  roles:
    - vagrant-newnode

- hosts: local
  become: true
  become_user: "{{ act_as }}"

  vars:
    node_group: "vault"
    node_read_only: true

  vars_files:
    - vars/variables.prod.yml

  roles:
    - vagrant-newnode

- hosts: vagrant_consul,vagrant_vault
  become: true

  vars:
    ansible_host_key_checking: false

  vars_files:
    - vars/consul_encrypt.prod.yml

  tasks:
    - shell: cat /etc/consul.d/consul.hcl
      register: consul_conf

    - debug:
        msg: "{{ consul_conf.stdout_lines }}"

#    - lineinfile:
#        path: /etc/consul.d/consul.hcl
#        state: absent
#        regexp: "^encrypt"

    - lineinfile:
        path: /etc/consul.d/consul.hcl
        line: "encrypt = \"{{ encryption_key }}\""
        insertafter:

    - shell: cat /etc/consul.d/consul.hcl
      register: consul_conf

    - debug:
        msg: "{{ consul_conf.stdout_lines }}"

- hosts: vagrant_consul,vagrant_vault
  become: true
  serial: true

  vars:
    ansible_host_key_checking: false

  tasks:
    - systemd:
        state: restarted
        name: consul

    - shell: consul keyring -list
      ignore_errors: true
      retries: 3
      delay: 3
      register: keyring_check
      until: keyring_check.rc == 0