# read nodes
- hosts: local
  become: true
  become_user: "{{ act_as }}"

  vars:
    node_groups:
      - consul
      - vault
    node_read_only: true

  vars_files:
    - vars/variables.prod.yml

  roles:
    - vagrant-newnode

- hosts: vagrant_consul
  become: true

  vars:
    ansible_host_key_checking: false

  roles:
    - consul-acl

- hosts: vagrant_vault
  become: true
  serial: true

  vars:
    ansible_host_key_checking: false

  tasks:
    - set_fact: agent_token="{{ hostvars[groups['vagrant_consul']|first].agent_tokens[ansible_hostname] }}"
    - set_fact: vault_server_token="{{ hostvars[groups['vagrant_consul']|first].vault_server_tokens[ansible_hostname] }}"
    - set_fact: vault_service_token="{{ hostvars[groups['vagrant_consul']|first].vault_service_tokens[ansible_hostname] }}"

    - name: Put ACL block
      blockinfile:
        path: /etc/consul.d/consul.hcl
        insertafter:
        block: |2

          acl {
            tokens {
              agent = "{{ agent_token }}"
              default = "{{ vault_server_token }}"
            }
          }

    - name: Remove block marker
      lineinfile:
        path: /etc/consul.d/consul.hcl
        state: absent
        regexp: ^# .* MANAGED BLOCK$

    - name: Restart consul service
      systemd:
        state: restarted
        name: consul

    - name: Remove existing vault service token
      lineinfile:
        path: /etc/vault.d/vault.hcl
        regexp: '^  token .*'
        state: absent

    - name: Put vault service token to vault conf
      lineinfile:
        path: /etc/vault.d/vault.hcl
        insertafter: "^\\s*path\\s*=\\s*\"vault/\""
        line: '  token   = "{{ vault_service_token }}"'

    - name: Restart vault service
      systemd:
        state: restarted
        name: vault

    - name: Check is vault service properly registered to consul
      shell: consul catalog services | grep vault

- hosts: vagrant_consul
  become: true

  vars:
    ansible_host_key_checking: false

  tasks:
    - name: Set default policy to deny
      lineinfile:
        path: /etc/consul.d/consul.hcl
        regexp: '  default_policy = "allow"'
        line: '  default_policy = "deny"'

    - name: Restart consul service
      systemd:
        state: restarted
        name: consul
