---
- hosts: local
  become: true

  vars:
    - node_clusters:
        - "192.168.58.11"
        - "192.168.58.12"
        - "192.168.58.13"
        - "192.168.58.21"
        - "192.168.58.22"
        - "192.168.58.23"

  tasks:
    - name: Put consul to inventory host
      add_host:
        name: "{{ node_ipv4_address }}"
        groupname: consul_cluster
        ansible_host: "{{ node_ipv4_address }}"
        ansible_user: vagrant
        ansible_python_interpreter: /usr/bin/python3
        host_key_checking: false
      loop: "{{ node_clusters }}"
      loop_control:
        loop_var: node_ipv4_address

- hosts: consul_cluster
  become: true
  serial: true

  vars:
    ansible_host_key_checking: false

  vars_prompt:
    - name: consul_version
      prompt: Which version will Consul be upgraded?
      private: no

  roles:
    - consul-upgrade
