# read nodes
- hosts: local
  become: true
  become_user: "{{ act_as }}"

  vars:
    node_group: "consul"
    node_read_only: true

  vars_files:
    - vars/variables.prod.yml

  roles:
    - vagrant-newnode

- hosts: local
  become: true
  become_user: "{{ act_as }}"

  vars:
    node_group: "vault"
    node_read_only: true

  vars_files:
    - vars/variables.prod.yml

  roles:
    - vagrant-newnode

- hosts: vagrant_consul
  become: true

  vars:
    ansible_host_key_checking: false

  tasks:
    - name: Put Consul ACL block
      blockinfile:
        path: /etc/consul.d/consul.hcl
        insertafter:
        block: |2

          acl {
            enabled = true
            default_policy = "allow"
            enable_token_persistence = true
          }

    - name: Remove block marker
      lineinfile:
        path: /etc/consul.d/consul.hcl
        state: absent
        regexp: ^# .* MANAGED BLOCK$

    - name: Restart consul service
      systemd:
        state: restarted
        name: consul

    - name: Set whos the first host
      set_fact:
        first_host: "{{ ansible_play_hosts|first }}"

    - name: Bootstraping consul ACL
      shell: consul acl bootstrap | tee /home/vagrant/consul_acl.txt
      register: consul_acl
      when: ansible_hostname == first_host

    - name: Save the global token
      set_fact:
        consul_token: "{{ hostvars[first_host].consul_acl.stdout_lines[1]|split(' ')|last }}"

    - name: Gathering data centers of each consul clients
      shell: consul members | grep {{ item }} | awk '{print $7}'
      register: consul_dcs
      when: ansible_hostname == first_host
      loop: "{{ groups['vagrant_vault'] }}"

    - name: Create consul agent token for each consul clients
      shell: |
        consul acl token create \
          -description "{{ item }} agent token" \
          -node-identity "{{ item }}:{{ consul_dcs.results[item_idx].stdout }}"
      environment:
        CONSUL_HTTP_TOKEN: "{{ consul_token }}"
      register: raw_agent_tokens
      when: ansible_hostname == first_host
      loop: "{{ groups['vagrant_vault'] }}"
      loop_control:
        index_var: item_idx

    - name: Create consul DNS request policy
      shell: |
        consul acl policy create -name "dns-requests" -rules - <<EOF
        node_prefix "" {
          policy = "read"
        }
        
        service_prefix "" {
          policy = "read"
        }
        EOF
      environment:
        CONSUL_HTTP_TOKEN: "{{ consul_token }}"
      register: dns_requests_policy
      when: ansible_hostname == first_host

    - name: Create consul DNS requests token for each consul clients
      shell: |
        consul acl token create \
          -description "{{ item }} dns requests token" \
          -policy-name dns-requests
          -node-identity "{{ item }}:{{ consul_dcs.results[item_idx].stdout }}"
      environment:
        CONSUL_HTTP_TOKEN: "{{ consul_token }}"
      register: raw_dns_tokens
      when: ansible_hostname == first_host
      loop: "{{ groups['vagrant_vault'] }}"
      loop_control:
        index_var: item_idx

- hosts: vagrant_vault
  become: true

  vars:
    ansible_host_key_checking: false

  tasks:
    - set_fact: raw_agent_tokens="{{ hostvars[groups['vagrant_consul']|first].raw_agent_tokens.results }}"
    - set_fact: agent_index="{{ lookup('ansible.utils.index_of', raw_agent_tokens, 'eq', ansible_hostname, 'item') }}"
    - set_fact: agent_token="{{ raw_agent_tokens[agent_index|int].stdout_lines[1]|split(' ')|last }}"

    - set_fact: raw_dns_tokens="{{ hostvars[groups['vagrant_consul']|first].raw_dns_tokens.results }}"
    - set_fact: dns_index="{{ lookup('ansible.utils.index_of', raw_dns_tokens, 'eq', ansible_hostname, 'item') }}"
    - set_fact: dns_token="{{ raw_dns_tokens[dns_index|int].stdout_lines[1]|split(' ')|last }}"

    - name: Put ACL block
      blockinfile:
        path: /etc/consul.d/consul.hcl
        insertafter:
        block: |2

          acl {
            tokens {
              agent = "{{ agent_token }}"
              default = "{{ dns_token }}"
            }
          }

    - name: Remove block marker
      lineinfile:
        path: /etc/consul.d/consul.hcl
        state: absent
        regexp: ^# .* MANAGED BLOCK$

    - name: Restart consul service
      systemd:
        state: restarted
        name: consul

- hosts: vagrant_consul
  become: true

  vars:
    ansible_host_key_checking: false

  tasks:
    - name: Set default policy to deny
      lineinfile:
        path: /etc/consul.d/consul.hcl
        regexp: "default_policy\\s*=\\s*\"allow\""
        line: default_policy = "deny"

    - name: Restart consul service
      systemd:
        state: restarted
        name: consul
