# read nodes
- hosts: local
  become: true
  become_user: "{{ act_as }}"

  vars:
    node_groups:
      - consul
      - vault
      - nomad
      - worker
    node_read_only: true

  vars_files:
    - vars/variables.prod.yml

  tasks:
    - set_fact:
        encryption_key: "{{ lookup('community.general.random_string', length=32, base64=True) }}"
      when: encryption_key is undefined

    - include_role:
        name: vagrant-newnode

- hosts: vagrant_consul
  become: true

  vars:
    ansible_host_key_checking: false

  roles:
    - consul-encrypt

- hosts: vagrant_*:!vagrant_consul
  become: true

  vars:
    ansible_host_key_checking: false

  roles:
    - consul-encrypt
