- hosts: local
  become: true
  become_user: "{{ act_as }}"

  vars:
    - public_key_path: "/home/{{ act_as }}/.ssh/id_rsa.pub"

  vars_files:
    - vars/variables.prod.yml

  roles:
    - vagrant-init
