- hosts: local
  become: true
  become_user: "{{ act_as }}"

  vars:
    - public_key_path: "/home/{{ act_as }}/.ssh/id_rsa.pub"
    - consul_clusters:
        - "192.168.58.11"
        - "192.168.58.12"
        - "192.168.58.13"
    - nomad_clusters:
        - "192.168.58.21"
        - "192.168.58.22"
        - "192.168.58.23"
    - worker_clusters:
        - "192.168.58.101"
        - "192.168.58.102"

  roles:
    - vagrant-init