### VAULT
# create nodes
- hosts: local
  become: true
  become_user: "{{ act_as }}"

  vars:
    node_group: "vault"

  vars_files:
    - vars/variables.prod.yml

  roles:
    - vagrant-newnode

# wait node ready
- hosts: vagrant_vault
  become: true
  gather_facts: no

  roles:
    - node-wait

# provision
- hosts: vagrant_vault
  become: true

  roles:
    - basic
    - consul-install
    - vault-install

# bootstrap seal token
- hosts: vagrant_vault
  become: true
  serial: true
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"

  roles:
    - vault-bootstrap
