### NOMAD
# create nodes
- hosts: local
  become: true
  become_user: "{{ act_as }}"

  vars:
    node_group: "nomad"
    node_clusters: "{{ nomad_clusters }}"

  vars_files:
    - vars/variables.prod.yml

  roles:
    - vagrant-newnode

# wait node ready
- hosts: vagrant_nomad
  become: true
  gather_facts: no

  vars:
    ansible_host_key_checking: false

  roles:
    - node-wait

# provision
- hosts: vagrant_nomad
  become: true

  vars:
    ansible_host_key_checking: false
    nomad_server: true

  roles:
    - basic
    - consul-install
    - nomad-install

# starting nomad
- hosts: vagrant_nomad
  become: true
  serial: true

  vars:
    ansible_host_key_checking: false

  tasks:
    - name: Restart nomad service
      systemd:
        name: nomad
        state: restarted
        enabled: true
        daemon_reload: yes

# bootstrap acl
- hosts: nomad-1
  become: true
  vars:
    ansible_host_key_checking: false

  roles:
    - nomad-bootstrap
