### CONSUL

# create nodes
- hosts: local
  become: true
  become_user: "{{ act_as }}"

  vars:
    node_group: "consul"

  vars_files:
    - vars/variables.prod.yml

  roles:
    - vagrant-newnode

# wait node ready
- hosts: vagrant_consul
  become: true
  gather_facts: no

  roles:
    - node-wait

# provision consul
- hosts: vagrant_consul
  become: true

  vars:
    consul_server: true
    consul_retry_join: "{{ groups['vagrant_consul'] | map('extract',hostvars,'ip_address') }}"

  roles:
    - basic
    - consul-install

# starting consul
- hosts: vagrant_consul
  become: true
  serial: true

  tasks:
    - name: Start consul service
      systemd:
        name: consul
        state: started
        enabled: true
        daemon_reload: yes
