### NOMAD
# create nodes
- hosts: local
  become: true
  become_user: "{{ act_as }}"

  vars:
    node_group: "nomad"

  vars_files:
    - vars/variables.prod.yml

  roles:
    - vagrant-newnode

# wait node ready
- hosts: vagrant_nomad
  become: true
  gather_facts: no

  roles:
    - node-wait

# provision
- hosts: vagrant_nomad
  become: true

  vars:
    nomad_server: true
    consul_retry_join: "{{ clusters['consul'] }}"

  vars_files:
    - vars/variables.prod.yml

  roles:
    - basic
    - consul-install
    - nomad-install

# starting nomad
- hosts: vagrant_nomad
  become: true
  serial: true

  tasks:
    - name: Restart nomad service
      systemd:
        name: nomad
        state: restarted
        enabled: true
        daemon_reload: yes

# bootstrap acl
- hosts: vagrant_nomad
  become: true
  serial: true

  vars_files:
    - vars/variables.prod.yml

  roles:
    - nomad-bootstrap
