### CONSUL

# create nodes
- hosts: local
  become: true
  become_user: "{{ act_as }}"

  vars:
    host_prefix: "consul"
    host_group: "vagrant_consul"

  vars_files:
    - vars/variables.prod.yml

  tasks:
    - include_role:
        name: vagrant-newnode
      loop: consul_clusters

# provision consul
- hosts: vagrant_consul
  become: true

  vars:
    ansible_host_key_checking: false
    consul_provision: true
    consul_server: true

  roles:
    - basic
    - consul-install

# starting consul
- hosts: vagrant_consul
  become: true
  serial: true

  vars:
    ansible_host_key_checking: false
    consul_starter: true

  roles:
    - consul-install
