### NOMAD
# create nodes
- hosts: local
  become: true
  become_user: "{{ act_as }}"

  vars:
    node_group: "nomad"
    node_clusters: "{{ nomad_clusters }}"

  vars_files:
    - vars/variables.prod.yml

  roles:
    - vagrant-newnode

# provision
- hosts: vagrant_nomad
  become: true
  gather_facts: no

  vars:
    ansible_host_key_checking: false
    nomad_server: true

  tasks:
    - name: Waiting for new instance ready
      wait_for_connection:
        timeout: 60

    - debug: msg="Ready to connect new node"

    - name: Gather node facts
      setup:

    - include_role:
        name: basic

    - include_role:
        name: consul-install

    - include_role:
        name: nomad-install

# starting nomad
- hosts: vagrant_nomad
  become: true
  serial: true

  vars:
    ansible_host_key_checking: false

  tasks:
    - name: Restart nomad service
      systemd:
        name: nomad
        state: restarted
        enabled: true
        daemon_reload: yes

# bootstrap acl
- hosts: nomad-1
  become: true
  vars:
    ansible_host_key_checking: false
    acl_filepath: /home/vagrant/.nomad

  roles:
    - nomad-bootstrap
