### CONSUL

# create nodes
- hosts: local
  become: true
  become_user: "{{ act_as }}"

  vars:
    node_group: "consul"

  vars_files:
    - vars/variables.prod.yml

  tasks:
    - include_role:
        name: vagrant-newnode
      loop: consul_clusters
      loop_control:
        loop_var: node
        index_var: node_idx

# provision consul
- hosts: vagrant_consul
  become: true

  vars:
    ansible_host_key_checking: false
    consul_server: true

  roles:
    - basic
    - consul-install

# starting consul
- hosts: vagrant_consul
  become: true
  serial: true

  vars:
    ansible_host_key_checking: false

  tasks:
    - name: Start consul service
      systemd:
        name: consul
        state: started
        enabled: true
        daemon_reload: yes
