---
- name: add hashicorp apt signing key
  shell: "curl -fsSL {{ hashi_key }} | apt-key add -"

- name: add vault repositories
  apt_repository:
    repo: "{{ hashi_repo }}"
    filename: vault
    state: present
    update_cache: no

- name: Installing latest vault version
  apt:
    name: vault
    state: present
    update-cache: true
  when: vault_version is undefined

- name: "Installing vault v{{ vault_version }}"
  apt:
    name: "vault={{ vault_version }}}"
    state: present
    update-cache: true
  when: vault_version is defined

- name: Put vault address exporter
  template:
    src: script.export-vault-addr.j2
    dest: /etc/profile.d/export-vault-addr.sh
    mode: 0755

- name: Set vault config to server mode
  template:
    src: conf.vault.server.j2
    dest: /etc/vault.d/vault.hcl
    owner: vault
    group: vault
    mode: 0600

- name: Restart vault service
  systemd:
    name: vault
    state: restarted
    enabled: true
    daemon_reload: yes
