---
- name: Setting up server's timezone
  timezone:
    name: "{{ timezone }}"

- name: Installing basics packages
  apt:
    name: "{{ basic_packages }}"
    state: present
    update-cache: true

- name: is hashicorp list exist
  stat:
    path: /etc/apt/sources.list.d/hashicorp.list
  register: hashi_repo

- name: create hashicorp list file
  file:
    path: /etc/apt/sources.list.d/hashicorp.list
    state: touch
    mode: 0644
  when: not hashi_repo.stat.exists

- name: put hashicorp gpg key and repo
  shell: |
    repo={{ hashicorp_repo }}
    key_path=/usr/share/keyrings/hashicorp.gpg
    src_path=/etc/apt/sources.list.d/hashicorp.list
    lsb={{ ansible_distribution_release }}
    wget -O- $repo/gpg | gpg --dearmor | tee $key_path > /dev/null
    echo "deb [signed-by=$key_path] $repo $lsb main" | tee $src_path > /dev/null
    apt update
  when: not hashi_repo.stat.exists
