---
- name: Installing latest nomad version
  apt:
    name: nomad
    state: present
    update-cache: true
  when: nomad_version is undefined

- name: "Installing nomad v{{ nomad_version }}"
  apt:
    name: "nomad={{ nomad_version }}}"
    state: present
    update-cache: true
  when: nomad_version is defined

- name: Create consul template directories
  file:
    path: "/opt/nomad/{{ item }}"
    state: directory
    mode: 0755
    owner: nomad
    group: nomad
  with_items:
    - agent-certs
    - cli-certs
    - templates

- name: Put consul template files
  template:
    src: "{{ item.tpl }}"
    dest: /opt/nomad/templates/{{ item.filename }}
    owner: nomad
    group: nomad
    mode: 0600
  with_items:
    - { tpl: conf.consul-template.j2, filename: consul-template.hcl }
    - { tpl: cert.cli.crt.j2, filename: cli.crt.tpl }
    - { tpl: cert.cli.key.j2, filename: cli.key.tpl }

- include_tasks: server.yml
  when: nomad_server is defined and nomad_server == true

- include_tasks: worker.yml
  when: nomad_server is undefined or nomad_server != true
