---
- name: add hashicorp apt signing key
  shell: "curl -fsSL {{ hashi_key }} | apt-key add -"

- name: add nomad repositories
  apt_repository:
    repo: "{{ hashi_repo }}"
    filename: nomad
    state: present
    update_cache: no

- name: Installing latest nomad version
  apt:
    name: nomad
    state: present
    update-cache: true
  when: nomad_version is undefined

- name: "Installing nomad v{{ nomad_version }}"
  apt:
    name: "nomad={{ nomad_version }}}"
    state: present
    update-cache: true
  when: nomad_version is defined

- include_tasks: server.yml
  when: nomad_server is defined and nomad_server == true

- include_tasks: worker.yml
  when: nomad_server is undefined or nomad_server != true
