---
- name: add hashicorp apt signing key
  shell: "curl -fsSL {{ hashi_key }} | apt-key add -"

- name: add consul repositories
  apt_repository:
    repo: "{{ hashi_repo }}"
    filename: nomad
    state: present
    update_cache: no

- name: Installing latest nomad version
  apt:
    name: nomad
    state: present
    update-cache: true
  when: nomad_version is undefined

- name: "Installing nomad v{{ nomad_version }}"
  apt:
    name: "nomad={{ nomad_version }}}"
    state: present
    update-cache: true
  when: nomad_version is defined

- name: Set nomad config to server mode
  template:
    src: conf.nomad.server.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: nomad
    group: nomad
    mode: 0600
  when: nomad_server is defined and nomad_server == true

- name: Set nomad config to client mode
  template:
    src: conf.nomad.worker.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: nomad
    group: nomad
    mode: 0600
  when: nomad_server is undefined or nomad_server != true

- name: Add nomad user to docker group
  user:
    name: nomad
    groups: docker
    append: yes
  when: nomad_server is undefined or nomad_server != true

- name: Restart nomad service
  systemd:
    name: nomad
    state: restarted
    enabled: true
    daemon_reload: yes
  when: nomad_server is undefined or nomad_server != true
