---
- name: Create consul template directories
  file:
    path: "/opt/nomad/{{ item }}"
    state: directory
    mode: 0755
    owner: nomad
    group: nomad
  with_items:
    - agent-certs
    - cli-certs
    - templates

- name: Put consul template files
  template:
    src: "{{ item.tpl }}"
    dest: /opt/nomad/templates/{{ item.filename }}
    owner: nomad
    group: nomad
    mode: 0644
  with_items:
    - { tpl: conf.consul-template.j2, filename: consul-template.hcl }
    - { tpl: cert.cli.crt.j2, filename: cli.crt.tpl }
    - { tpl: cert.cli.key.j2, filename: cli.key.tpl }

- name: Put consul template service
  template:
    src: service.consul-template.j2
    dest: /usr/lib/systemd/system/consul-template.service
    owner: nomad
    group: nomad
    mode: 0644

- name: Put server agent certificate template
  template:
    src: cert.{{ item.tpl }}.j2
    dest: /opt/nomad/templates/{{ item.filename }}.tpl
    owner: nomad
    group: nomad
    mode: 0644
  with_items:
    - { tpl: ca.crt, filename: ca.crt }
    - { tpl: server.crt, filename: agent.crt }
    - { tpl: server.key, filename: agent.key }
  when: nomad_server is defined and nomad_server == true

- name: Put worker agent certificate template
  template:
    src: cert.{{ item.tpl }}.j2
    dest: /opt/nomad/templates/{{ item.filename }}.tpl
    owner: nomad
    group: nomad
    mode: 0644
  with_items:
    - { tpl: ca.crt, filename: ca.crt }
    - { tpl: worker.crt, filename: agent.crt }
    - { tpl: worker.key, filename: agent.key }
  when: nomad_server is undefined or nomad_server != true

- name: Restart consul template service
  systemd:
    name: consul-template
    state: restarted
    enabled: true
    daemon_reload: yes

- name: Wait consul-template generate certificate
  wait_for:
    path: /opt/nomad/agent-certs/agent.crt
    state: present
    timeout: "{{ sleep_in_between|default(30) }}"

- name: Exporting cli cert to p12 keystore
  shell: openssl pkcs12 -export -out keystore.p12 -inkey cli.key -in cli.crt
  args:
    chdir: /opt/nomad/cli-certs

- name: Export nomad tls environment variables
  shell: |
    echo 'export NOMAD_ADDR="https://127.0.0.1:4646"' >> ~/.bashrc
    echo 'export NOMAD_CACERT="/opt/nomad/agent-certs/ca.crt"' >> ~/.bashrc
    echo 'export NOMAD_CLIENT_CERT="/opt/nomad/cli-certs/cli.crt"' >> ~/.bashrc
    echo 'export NOMAD_CLIENT_KEY="/opt/nomad/cli-certs/cli.key"' >> ~/.bashrc
  become: true
  become_user: vagrant
