---
- name: Put cli certificate template
  template:
    src: cert.{{ item.tpl }}.j2
    dest: /opt/nomad/templates/{{ item.filename }}.tpl
    owner: nomad
    group: nomad
    mode: 0600
  with_items:
    - { tpl: ca.crt, filename: ca.crt }
    - { tpl: server.crt, filename: agent.crt }
    - { tpl: server.key, filename: agent.key }

- name: Get first play hostname
  set_fact:
    first_play_hostname: "{{ ansible_play_hosts|first }}"

- name: Generate nomad gossip keyring
  shell: nomad operator gossip keyring generate
  register: gossip_key
  when: ansible_hostname == first_play_hostname

- set_fact:
    nomad_gossip_key: "{{ gossip_key.stdout }}"
  when: ansible_hostname == first_play_hostname

- set_fact:
    nomad_gossip_key: "{{ hostvars[first_play_hostname].nomad_gossip_key }}"
  when: ansible_hostname != first_play_hostname

- name: Set nomad config to server mode
  template:
    src: conf.nomad.server.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: nomad
    group: nomad
    mode: 0600
