- name: Set nomad config to client mode
  template:
    src: conf.nomad.worker.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: nomad
    group: nomad
    mode: 0600

- name: Check is docker group exist
  getent:
    database: group
    key: docker
  register: is_docker_group_exist
  ignore_errors: true

- name: Add nomad user to docker group
  user:
    name: nomad
    groups: docker
    append: yes
  when:
    - not is_docker_group_exist.failed
    - ansible_facts.getent_group|length > 0

- name: Restart nomad service
  systemd:
    name: nomad
    state: restarted
    enabled: true
    daemon_reload: yes

- name: Create CNI bin directory
  file:
    path: /opt/cni/bin
    state: directory
    mode: 0755

- name: Download CNI
  get_url:
    url: "https://github.com/containernetworking/plugins/releases/download/v{{ cni_version }}/cni-plugins-linux-amd64-v{{ cni_version }}.tgz"
    dest: "/tmp/cni-plugins-linux-amd64-v{{ cni_version }}.tgz"
    mode: 0755

- name: Extract CNI file
  unarchive:
    src: "/tmp/cni-plugins-linux-amd64-v{{ cni_version }}.tgz"
    dest: /opt/cni/bin
    remote_src: yes
