---
- name: "Delete node {{ item.hostname }} if available"
  shell: "vagrant destroy -f {{ item.hostname }}"
  args:
    chdir: "{{ playbook_dir }}"
  ignore_errors: true

- name: "Bootstrapping node {{ item.hostname }}"
  shell: "vagrant up {{ item.hostname }}"
  args:
    chdir: "{{ playbook_dir }}"
  register: new_node_status

- debug: var=new_node_status['stdout_lines']

- name: "Put {{ item.hostname }} to inventory host"
  add_host:
    name: "{{ item.ipv4_address }}"
    groupname: "{{ item.group_name }}"
    ansible_user: vagrant
    ansible_python_interpreter: /usr/bin/python3
    host_key_checking: false