---
- set_fact:
    node_clusters: "{{ clusters[node_group] }}"

- set_fact:
    node_hostnames: "{{ node_clusters|map('last')|product([node_group])|map('reverse')|map('join', '-')|join(' ') }}"
    node_group_name: "vagrant_{{ node_group }}"

- name: "Delete node {{ node_hostnames }} if available"
  shell: "vagrant destroy -f {{ node_hostnames }}"
  args:
    chdir: "{{ playbook_dir }}"
  ignore_errors: true
  when: node_read_only | default(false) == false

- name: "Bootstrapping node {{ node_hostnames }}"
  shell: "vagrant up {{ node_hostnames }}"
  args:
    chdir: "{{ playbook_dir }}"
  register: new_node_status
  when: node_read_only | default(false) == false

- debug: var=new_node_status['stdout_lines']
  when: node_read_only | default(false) == false

- name: "Put {{ node_hostnames }} to inventory host"
  add_host:
    name: "{{ node_group }}-{{ node_ipv4_address|last }}"
    groupname: "{{ node_group_name }}"
    ansible_host: "{{ node_ipv4_address }}"
    ansible_user: vagrant
    ansible_port: 22
    ansible_python_interpreter: /usr/bin/python3
    host_key_checking: false
  loop: "{{ node_clusters }}"
  loop_control:
    loop_var: node_ipv4_address