---
- name: Delete existing node if available
  shell: "vagrant destroy -f {{ new_node.hostname }}"
  args:
    chdir: "{{ playbook_dir }}"
  ignore_errors: true

- name: Bootstrapping node
  shell: "vagrant up {{ new_node.hostname }}"
  args:
    chdir: "{{ playbook_dir }}"
  register: new_node_status

- debug: var=new_node_status['stdout_lines']

- name: Put consul to inventory host
  add_host:
    name: "{{ new_node.ipv4_address }}"
    groupname: vagrant_consul
    ansible_user: vagrant
    ansible_python_interpreter: /usr/bin/python3
    host_key_checking: false